# Generated by Django 3.0.2 on 2020-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webrequest',
            name='client_ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
